package trabalho;
// Generated 17/05/2019 16:35:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Duplicatas generated by hbm2java
 */
public class Duplicatas  implements java.io.Serializable {


     private Integer codigo;
     private int sequencial;
     private int codContrato;
     private Date dataVencimento;
     private Double valor;

    public Duplicatas() {
    }

	
    public Duplicatas(int sequencial, int codContrato) {
        this.sequencial = sequencial;
        this.codContrato = codContrato;
    }
    public Duplicatas(int sequencial, int codContrato, Date dataVencimento, Double valor) {
       this.sequencial = sequencial;
       this.codContrato = codContrato;
       this.dataVencimento = dataVencimento;
       this.valor = valor;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public int getSequencial() {
        return this.sequencial;
    }
    
    public void setSequencial(int sequencial) {
        this.sequencial = sequencial;
    }
    public int getCodContrato() {
        return this.codContrato;
    }
    
    public void setCodContrato(int codContrato) {
        this.codContrato = codContrato;
    }
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }




}