package trabalho;
// Generated 17/05/2019 16:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoas generated by hbm2java
 */
public class Pessoas  implements java.io.Serializable {


     private Integer codigo;
     private String tipo;
     private String cpf;
     private String nome;
     private String cnpj;
     private String classificacao;
     private String estadoCivil;
     private String estado;
     private String celular;
     private String bairro;
     private String endereco;
     private String telefone;
     private String cidade;
     private String login;
     private String senha;
     private Set servicoscontratos = new HashSet(0);
     private Set contratoses = new HashSet(0);

    public Pessoas() {
    }

	
    public Pessoas(String tipo, String classificacao, String estadoCivil, String estado) {
        this.tipo = tipo;
        this.classificacao = classificacao;
        this.estadoCivil = estadoCivil;
        this.estado = estado;
    }
    public Pessoas(String tipo, String cpf, String nome, String cnpj, String classificacao, String estadoCivil, String estado, String celular, String bairro, String endereco, String telefone, String cidade, String login, String senha, Set servicoscontratos, Set contratoses) {
       this.tipo = tipo;
       this.cpf = cpf;
       this.nome = nome;
       this.cnpj = cnpj;
       this.classificacao = classificacao;
       this.estadoCivil = estadoCivil;
       this.estado = estado;
       this.celular = celular;
       this.bairro = bairro;
       this.endereco = endereco;
       this.telefone = telefone;
       this.cidade = cidade;
       this.login = login;
       this.senha = senha;
       this.servicoscontratos = servicoscontratos;
       this.contratoses = contratoses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(String classificacao) {
        this.classificacao = classificacao;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getServicoscontratos() {
        return this.servicoscontratos;
    }
    
    public void setServicoscontratos(Set servicoscontratos) {
        this.servicoscontratos = servicoscontratos;
    }
    public Set getContratoses() {
        return this.contratoses;
    }
    
    public void setContratoses(Set contratoses) {
        this.contratoses = contratoses;
    }
    
    @Override
    public String toString() {
        return nome;
    }




}


