package trabalho;
// Generated 17/05/2019 16:35:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contratos generated by hbm2java
 */
public class Contratos  implements java.io.Serializable {


     private Integer codContrato;
     private Pessoas pessoas;
     private Date dataInicial;
     private Date dataFim;
     private String situacao;
     private Double valorContrato;
     private String condPagamento;
     private Set servicoscontratos = new HashSet(0);

    public Contratos() {
    }

	
    public Contratos(Pessoas pessoas, String situacao) {
        this.pessoas = pessoas;
        this.situacao = situacao;
    }
    public Contratos(Pessoas pessoas, Date dataInicial, Date dataFim, String situacao, Double valorContrato, String condPagamento, Set servicoscontratos) {
       this.pessoas = pessoas;
       this.dataInicial = dataInicial;
       this.dataFim = dataFim;
       this.situacao = situacao;
       this.valorContrato = valorContrato;
       this.condPagamento = condPagamento;
       this.servicoscontratos = servicoscontratos;
    }
   
    public Integer getCodContrato() {
        return this.codContrato;
    }
    
    public void setCodContrato(Integer codContrato) {
        this.codContrato = codContrato;
    }
    public Pessoas getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Date getDataInicial() {
        return this.dataInicial;
    }
    
    public void setDataInicial(Date dataInicial) {
        this.dataInicial = dataInicial;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public Double getValorContrato() {
        return this.valorContrato;
    }
    
    public void setValorContrato(Double valorContrato) {
        this.valorContrato = valorContrato;
    }
    public String getCondPagamento() {
        return this.condPagamento;
    }
    
    public void setCondPagamento(String condPagamento) {
        this.condPagamento = condPagamento;
    }
    public Set getServicoscontratos() {
        return this.servicoscontratos;
    }
    
    public void setServicoscontratos(Set servicoscontratos) {
        this.servicoscontratos = servicoscontratos;
    }




}


