package trabalho;
// Generated 17/05/2019 16:35:06 by Hibernate Tools 4.3.1



/**
 * Servicoscontrato generated by hbm2java
 */
public class Servicoscontrato  implements java.io.Serializable {


     private Integer codigo;
     private Contratos contratos;
     private Pessoas pessoas;
     private Servicos servicos;
     private Double valor;
     private String observacao;

    public Servicoscontrato() {
    }

	
    public Servicoscontrato(Contratos contratos, Pessoas pessoas, Servicos servicos) {
        this.contratos = contratos;
        this.pessoas = pessoas;
        this.servicos = servicos;
    }
    public Servicoscontrato(Contratos contratos, Pessoas pessoas, Servicos servicos, Double valor, String observacao) {
       this.contratos = contratos;
       this.pessoas = pessoas;
       this.servicos = servicos;
       this.valor = valor;
       this.observacao = observacao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Contratos getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Contratos contratos) {
        this.contratos = contratos;
    }
    public Pessoas getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Pessoas pessoas) {
        this.pessoas = pessoas;
    }
    public Servicos getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Servicos servicos) {
        this.servicos = servicos;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


