package trabalho;
// Generated 17/05/2019 16:35:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicos generated by hbm2java
 */
public class Servicos  implements java.io.Serializable {


     private Integer codServico;
     private String descricao;
     private String descricaoComplementar;
     private Set servicoscontratos = new HashSet(0);

    public Servicos() {
    }

	
    public Servicos(String descricao) {
        this.descricao = descricao;
    }
    public Servicos(String descricao, String descricaoComplementar, Set servicoscontratos) {
       this.descricao = descricao;
       this.descricaoComplementar = descricaoComplementar;
       this.servicoscontratos = servicoscontratos;
    }
   
    public Integer getCodServico() {
        return this.codServico;
    }
    
    public void setCodServico(Integer codServico) {
        this.codServico = codServico;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getDescricaoComplementar() {
        return this.descricaoComplementar;
    }
    
    public void setDescricaoComplementar(String descricaoComplementar) {
        this.descricaoComplementar = descricaoComplementar;
    }
    public Set getServicoscontratos() {
        return this.servicoscontratos;
    }
    
    public void setServicoscontratos(Set servicoscontratos) {
        this.servicoscontratos = servicoscontratos;
    }




}


